services:
  - type: web
    name: yellowyr-bot
    env: node
    plan: free          # ou starter para uptime 24/7 sem sleep
    branch: main
    buildCommand: "npm install"
    startCommand: "node ."
    autoDeploy: true
    envVars:
      - key: TOKEN
        value: "SEU_DISCORD_TOKEN"
      - key: CLIENT_ID
        value: "SEU_DISCORD_CLIENT_ID"
      - key: MONGO_URI
        value: "SUA_MONGO_URI"
      - key: PREFIX
        value: "!"
